WebApp.Web/WebApp.Web/Controllers/HomePageController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Mappers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Distributed;
    using Microsoft.Extensions.DependencyInjection;
    using Models.Event;
    using Newtonsoft.Json;
    using Services.EventService;
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    public class HomePageController : BaseController
    {
        private readonly IEventService eventService;
        private readonly IEventMapper eventMapper;
        private readonly IDistributedCache distributedCache;
        private readonly UserManager<WebAppUser> userManager;

        public HomePageController(
            IServiceProvider provider,
            IServiceScopeFactory factory,
            IDistributedCache distributedCache,
            UserManager<WebAppUser> userManager,
            IEventService eventService,
            IEventMapper eventMapper) : base(provider, factory)
        {
            this.distributedCache = distributedCache;
            this.userManager = userManager;
            this.eventService = eventService;
            this.eventMapper = eventMapper;
        }

        public IActionResult HomePageView()
        {
            return ReturnMainView();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> HomePageView(EventBindingModel model, IFormFile eventImage)
        {
            this.eventService.CreateEvent(eventMapper.NewEvent(model, eventImage, userManager.GetUserId(User)));

            await base.UpdateEventsInCache();

            return ReturnMainView();
        }

        [Authorize]
        public IActionResult DetermineEventView(int Id)
        {
            Event currentEvent = eventService.GetEvent(Id);

            if (currentEvent.AdminId == userManager.GetUserId(User))
                return RedirectToAction("AdminViewEvent", "AdminEvent", currentEvent);
            else
                return RedirectToAction("ViewEvent", "Event", currentEvent);
        }

        [Authorize]
        private IActionResult ReturnMainView()
        {
            HomePageBinding model = new HomePageBinding();

            var events = GetEvents();

            foreach (var currentEvent in events)
            {
                if (!currentEvent.IsDeleted)
                    model.Events.Add(eventMapper.ViewEvent(currentEvent));
            }

            return View(model);
        }

        public IActionResult SearchForEvent(string searchedEvent)
        {
            HomePageBinding model = new HomePageBinding();

            var events = GetEvents();

            if (!string.IsNullOrEmpty(searchedEvent))
            {
                events = events.Where(e => e.Location.Contains(searchedEvent)).ToArray();
            }

            foreach (var currentEvent in events)
            {
                model.Events.Add(eventMapper.ViewEvent(currentEvent));
            }

            return View("HomePageView", model);
        }

        private Event[] GetEvents()
        {
            var events = this.distributedCache.GetString("events");
            return JsonConvert.DeserializeObject<Event[]>(events);
        }
    }
}

WebApp.Web/WebApp.Web/Controllers/UsersController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.ScoreService;
    using System.Collections.Generic;
    using System.Linq;

    public class UsersController : BaseController
    {
        private readonly UserManager<WebAppUser> userManager;
        private readonly IScoreService scoreService;

        public UsersController(UserManager<WebAppUser> userManager, IScoreService scoreService)
        {
            this.userManager = userManager;
            this.scoreService = scoreService;
        }

        [Authorize]
        public IActionResult Profile(string name)
        {
            UserBindingModel model = new UserBindingModel
            {
                Name = name,
                Score = GetUserScores(name)
            };

            return View("Profile", model);
        }

        private List<UserScore> GetUserScores(string name)
        {
            string id = userManager.Users.FirstOrDefault(u => u.UserName == name).Id;
            List<Rating> rating = scoreService.GetAllData().Where(rid => rid.ReceiverId == id).ToList();
            List<UserScore> userScores = new List<UserScore>();
            foreach (var item in rating)
            {
                foreach (var score in item.Scores)
                {
                    userScores.Add(new UserScore()
                    {
                        CurrentDate = score.DateTime.ToShortDateString(),
                        Score = score.Points
                    });
                }
            }

            return userScores;
        }
    }
}

WebApp.Web/WebApp.Web/Views/HomePage/HomePageView.cshtml
@model HomePageBinding
@{
    ViewData["Title"] = "Home";
}

<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />

</head>


<div class="container-fluid">

    @await Html.PartialAsync($"_NavBarPartial")
    <div class="row">
        <div class="col p-0 m-0" style="background-color: whitesmoke">

            <nav class="navbar p-0 m-0 justify-content-center d-flex bd-highlight sticky-top" id="centerNav">
                <form asp-controller="HomePage" asp-action="SearchForEvent" class="form-inline mt-2 bd-highlight">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search events by location" id="searchForm" name="searchedEvent">
                        <div class="input-group-append">
                            <button class="btn" id="searching">
                                <img src="~/images/homepage/icons8-search-48.png" style="width: 2vw" />
                            </button>
                        </div>
                    </div>
                </form>
                
                @if (this.User.Identity.IsAuthenticated)
                {
                    <button type="button" class="btn btn-outline-info mb-2 bd-highlight" data-toggle="modal" data-target="#exampleModalCenter" style="margin-left: 4rem">
                        Create Event
                    </button>
                }
            </nav>


            <div class="container d-flex justify-content-center" style="background-color: whitesmoke; z-index: -1">
                <div class="col">
                    @for (int i = 0; i < @Model.Events.Count(); i++)
                    {
                        @await Html.PartialAsync($"_EventDescriptionPartial", @Model.Events.ElementAt(i))
                    }
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <form asp-action="HomePageView" method="post" enctype="multipart/form-data">
                            <div class="modal-header d-flex justify-content-center">
                                <div class="form-group" style="width: 20rem">
                                    <input asp-for="@Model.Modal.Title" type="text" class="form-control" id="Title"  name="Title" required aria-describedby="TitleInput" placeholder="Event Title" />
                                </div>
                            </div>

                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea">Description</label>
                                    <textarea asp-for="@Model.Modal.Description" class="form-control" id="Description" name="Description" required rows="3"></textarea>
                                </div>
                                <div class="form-group" style="width: 20rem">
                                    <input asp-for="@Model.Modal.Location" type="text" class="form-control" id="Location " name="Location" required aria-describedby="TitleInput" placeholder="Event Location" />
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Example select</label>
                                    <select asp-for="@Model.Modal.SportId" class="form-control" id="exampleFormControlSelect1" name="SportId" required>
                                        <option value="1">Football</option>
                                    </select>
                                </div>

                                <label for="time"><br>Select Time and Date</label>
                                <input asp-for="@Model.Modal.Time" type="datetime-local" id="time" name="Time" required value="2019-01-01T12:00">

                                <div class="form-group">
                                    <br> Your image: <input type="file" name="eventImage" id="eventImage" accept="image/jpg"><br>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <input type="submit" value="Create Event" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .container-fluid, .row, .ul, body {
        margin: 0;
        padding: 0
    }

    #centerNav {
        height: 8vh;
        z-index: 999;
    }

    li {
        padding-top: 2rem;
        text-decoration: none
    }


    a {
        padding: 0;
        margin: 0;
    }

    img {
        border-radius: 50%;
        width: 100px
    }


    form {
        width: 30vw;
    }

    #searchForm {
        border-radius: 0;
        background-color: rgba(58,128,242,0.7);
        border: none;
        border-bottom: 1px solid lightgrey;
        height: 6vh;
        width: 26vw;
        border-radius: 10px;
    }

        #searchForm::-webkit-input-placeholder {
            color: white;
        }

        #searchForm:focus, #searchForm:active {
            outline: none !important;
            background-color: #3a80f2;
            box-shadow: none;
            border: none;
            border-bottom: solid 1px lightgrey;
            color: white;
        }

    button:focus {
        outline: 0 !important;
        box-shadow: none;
    }

    .jumbotron {
        width: 50vw;
        /*height: 40vh;*/
        border-radius: 20px;
    }
</style>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

WebApp.Web/WebApp.Web/Views/HomePage/_EventDescriptionPartial.cshtml
@model EventBindingModel

<div class="d-flex flex-row bd-highlight justify-content-center">
    <div class="jumbotron p-0 mt-5 bg-primary shadow" style="width:900px; margin-left:200px">
        <div class="d-flex justify-content-between">
            <h3 class="pt-2 pl-3">@Model.Title</h3>
            <h5 class="mt-3">@Model.Location</h5>
            <h6 class="mt-3 mr-3 ">Admin: @Model.AdminName</h6>
        </div>
        <hr class="mt-1 mb-3">

        <h5>TEAM 1</h5>
        @foreach (var position in Model.Positions.Take(Model.Positions.Count / 2).ToList())
        {
            IDictionary<string, string> rv = new Dictionary<string, string>();
            rv.Add("eventId", Model.Id.ToString());
            rv.Add("positionId", position.Id.ToString());
            StarModel starModel = new StarModel(position.EventId, position.Approved);
            <div class="row">
                <div class="col">
                    @position.Name:
                </div>
                <div class="col">
                    @if (@position.Approved.Name != null)
                    {
                        <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@position.Approved.Name">@position.Approved.Name</a>
                    }
                    else
                    {
                        <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled">Awaiting...</button>
                    }
                </div>
                <div class="col">
                    @if (@position.Approved.Name != null)
                    {
                        @await Html.PartialAsync($"_StarRatingPartial", starModel)
                    }
                </div>
                <div class="col">
                    @if (position.ToBeApproved.Exists(u => u.Name == User.Identity.Name))
                    {
                        <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
                    }
                    else if (@position.Approved.Name == null)
                    {
                        <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-all-route-data="@rv" asp-action="JoinUser">Join</a>
                    }
                    else if (@position.Approved.Name == User.Identity.Name)
                    {
                        <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
                    }
                    else if (Model.AdminName == User.Identity.Name)
                    {
                        <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Kick out</a>
                    }
                    else
                    {
                        <a></a>
                    }
                </div>
            </div>
        }
        <h5>TEAM 2</h5>
        @foreach (var position in Model.Positions.TakeLast(Model.Positions.Count / 2).ToList())
         {
            IDictionary<string, string> rv = new Dictionary<string, string>();
            rv.Add("eventId", Model.Id.ToString());
            rv.Add("positionId", position.Id.ToString());
            StarModel starModel = new StarModel(position.EventId, position.Approved);
            <div class="row">
                <div class="col">
                    @position.Name:
                </div>
                <div class="col">
                    @if (@position.Approved.Name != null)
                    {
                        <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@position.Approved.Name">@position.Approved.Name</a>
                    }
                    else
                    {
                        <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled">Awaiting...</button>
                    }
                </div>
                <div class="col">
                    @if (@position.Approved.Name != null)
                    {
                        @await Html.PartialAsync($"_StarRatingPartial", starModel)
                    }
                </div>
                <div class="col">
                    @if (position.ToBeApproved.Exists(u => u.Name == User.Identity.Name))
                    {
                        <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
                    }
                    else if (@position.Approved.Name == null)
                    {
                        <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-all-route-data="@rv" asp-action="JoinUser">Join</a>
                    }
                    else if (@position.Approved.Name == User.Identity.Name)
                    {
                        <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
                    }
                    else if (Model.AdminName == User.Identity.Name)
                    {
                        <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Kick out</a>
                    }
                    else
                    {
                        <a></a>
                    }
                </div>
            </div>
         }

        <hr class="my-2">
        <div class="d-flex justify-content-center">
            <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="HomePage" asp-route-id="@Model.Id" asp-action="DetermineEventView">Info</a>
        </div>
    </div>
</div>

<style>
    hr {
        background-color: bisque
    }

    a {
        color: white
    }

    a:hover, a:focus {
        background-color: transparent
    }
</style>



<script>
    src = "~/lib/bootstrap/dist/js/bootstrap.js";
    src = "~/js/site.js";
    src = "~/lib/jquery/dist/jquery.js";
</script>