WebApp.Web/WebApp.Web/Controllers/AdminEventController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Mappers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.DependencyInjection;
    using Models;
    using Models.Event;
    using Services.EventAttendanceService;
    using Services.EventService;
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    public class AdminEventController : BaseController
    {
        private readonly UserManager<WebAppUser> userManager;
        private readonly IEventService eventService;
        private readonly IEventMapper eventMapper;
        private readonly IEventAttendanceService attendanceService;

        public AdminEventController(
            UserManager<WebAppUser> userManager,
            IEventService eventService,
            IEventMapper eventMapper,
            IEventAttendanceService attendanceService,
            IServiceProvider provider,
            IServiceScopeFactory factory) : base(provider, factory)
        {
            this.userManager = userManager;
            this.eventService = eventService;
            this.eventMapper = eventMapper;
            this.attendanceService = attendanceService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult AdminViewEvent(Event dbEvent)
        {
            var model = eventMapper.ViewEvent(dbEvent);
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult GetMyEvents()
        {
            var userId = userManager.GetUserId(User);

            if (userId == null)
            {
                return BadRequest("No such User registered!");
            }

            var allMappedEventsByUser = new List<EventBindingModel>();

            var allEventsByUser = eventService.GetAllEventsByUser(userId);

            foreach (var eventByUser in allEventsByUser)
            {
                allMappedEventsByUser.Add(eventMapper.ViewEvent(eventByUser));
            }

            return View(allMappedEventsByUser);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DeleteEvent(int id)
        {
            await eventService.DeleteEvent(id);

            await base.UpdateEventsInCache();

            return RedirectToAction(nameof(GetMyEvents));
        }

        [Authorize]
        public async Task<IActionResult> Edit(EventBindingModel model, IFormFile eventImage)
        {
            var viewModel = eventMapper.ModifiedEvent(model, eventImage, userManager.GetUserId(User));
            this.eventService.EditEvent(viewModel);

            await base.UpdateEventsInCache();

            return this.RedirectToAction("GetMyEvents");
        }

        [Authorize]
        public IActionResult ApproveUser(ApproveOrIgnoreUserModel model)
        {
            int eventId = model.EventId;
            int positionId = model.PositionId;
            string userId = model.UserId;

            attendanceService.ApproveUserForeEvent(userId, eventId, positionId).Wait();
            return RedirectToAction("DetermineEventView", "HomePage", new { Id = eventId });
        }

        [Authorize]
        public IActionResult IgnoreUser(ApproveOrIgnoreUserModel model)
        {
            int eventId = model.EventId;
            int positionId = model.PositionId;
            string userId = model.UserId;

            attendanceService.RemoveUserAttendeeToBeApproved(userId, eventId, positionId);
            return RedirectToAction("DetermineEventView", "HomePage", new { Id = eventId });
        }
    }
}

WebApp.Web/WebApp.Web/Controllers/UsersController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.ScoreService;
    using System.Collections.Generic;
    using System.Linq;

    public class UsersController : BaseController
    {
        private readonly UserManager<WebAppUser> userManager;
        private readonly IScoreService scoreService;

        public UsersController(UserManager<WebAppUser> userManager, IScoreService scoreService)
        {
            this.userManager = userManager;
            this.scoreService = scoreService;
        }

        [Authorize]
        public IActionResult Profile(string name)
        {
            UserBindingModel model = new UserBindingModel
            {
                Name = name,
                Score = GetUserScores(name)
            };

            return View("Profile", model);
        }

        private List<UserScore> GetUserScores(string name)
        {
            string id = userManager.Users.FirstOrDefault(u => u.UserName == name).Id;
            List<Rating> rating = scoreService.GetAllData().Where(rid => rid.ReceiverId == id).ToList();
            List<UserScore> userScores = new List<UserScore>();
            foreach (var item in rating)
            {
                foreach (var score in item.Scores)
                {
                    userScores.Add(new UserScore()
                    {
                        CurrentDate = score.DateTime.ToShortDateString(),
                        Score = score.Points
                    });
                }
            }

            return userScores;
        }
    }
}

WebApp.Web/WebApp.Web/Views/AdminEvent/AdminViewEvent.cshtml
@{
    ViewData["Title"] = "Event";
    Layout = null;
}
@model EventBindingModel
<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />
</head>
<div class="container">
    <div id="sidebar">
        @await Html.PartialAsync("_NavBarPartial")
    </div>
    <div id="content">
        <div class="row">
            <div class="column">
                <img src=@Model.ImageURL id="EventImage" />
                <center>@Model.Location</center>
            </div>
            <div class="column">
                <center><h1>@Model.Title<h3>@Model.Time</h3></h1></center>
                <br />
                <br />
                <center>@Model.Description</center>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <h3><center>TEAM 1</center></h3>
                @await Html.PartialAsync($"_TeamPartial", Model.Positions.Take(Model.Positions.Count / 2).ToList())
            </div>
            <div class="column">
                <h3><center>TEAM 2</center></h3>
                @await Html.PartialAsync($"_TeamPartial", Model.Positions.TakeLast(Model.Positions.Count / 2).ToList())
            </div>
        </div>
        <center>
            <button type="button" class="btn btn-danger mx-3 mb-2" data-toggle="modal" data-target="#exampleModalCenter" id="editButton">
                Edit
            </button>
            <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="AdminEvent" asp-action="DeleteEvent" asp-route-id="@Model.Id" id="deleteButton">Delete</a>
            <!-- Modal -->
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <form asp-action="Edit" method="post" enctype="multipart/form-data">
                            <div class="modal-header d-flex justify-content-center">
                                <div class="form-group" style="width: 20rem">
                                    <input asp-for="@Model.Title" type="text" class="form-control" id="Title" name="Title" required aria-describedby="TitleInput" placeholder="Event Title" />
                                </div>
                            </div>

                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea">Description</label>
                                    <textarea asp-for="@Model.Description" class="form-control" id="Description" name="Description" required rows="3"></textarea>
                                </div>
                                <div class="form-group" style="width: 20rem">
                                    <input asp-for="@Model.Location" type="text" class="form-control" id="Location " name="Location" required aria-describedby="TitleInput" placeholder="Event Location" />
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Example select</label>
                                    <select asp-for="@Model.SportId" class="form-control" id="exampleFormControlSelect1" name="SportId" required>
                                        <option value="1">Football</option>
                                    </select>
                                </div>

                                <label for="time"><br>Select Time and Date</label>
                                <input asp-for="@Model.Time" type="datetime-local" id="time" name="Time" required value="2019-01-01T12:00">

                                <div class="form-group">
                                    <br> Your image: <input type="file" name="eventImage" id="eventImage" accept="image/jpg"><br>
                                </div>
                            </div>
                            <input type="hidden" asp-for="@Model.Id" />
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <input type="submit" value="Save" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </center>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
    }

    .container {
        position: relative;
        padding: 10px;
        top: 0px;
        right: 0;
        left: 0;
        height: 1200px;
        width: 100%;
        min-width: 1000px;
    }

    #sidebar {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        width: 200px;
        height: 1000px;
    }

    #content {
        height: 700px;
        margin-left: 200px;
        padding: 10px;
    }

    #EventImage {
        position: relative;
        display: block;
        margin-left: auto;
        margin-right: auto;
        z-index: 1;
        margin-right: auto;
        height: 100%;
        max-height: 300px;
        width: 100%;
        max-width: 600px;
    }

    .column {
        float: left;
        width: 50%;
    }

    .button {
        background-color: black;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 22px;
        margin: 4px 2px;
        cursor: pointer;
    }

    #deleteButton {
        background-color: red;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 22px;
        margin: 4px 2px;
        cursor: pointer;
    }

    #editButton {
        background-color: orange;
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 22px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


WebApp.Web/WebApp.Web/Views/AdminEvent/GetMyEvents.cshtml
@model IEnumerable<EventBindingModel>

@{
    ViewData["Title"] = "My Events";
}

<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />
</head>
<div class="container">
    <div id="sidebar">
        @await Html.PartialAsync("_NavBarPartial")
    </div>

    @foreach (var userEvent in Model)
    {
        <div class="d-flex flex-row bd-highlight justify-content-center">
            <div class="jumbotron p-0 mt-5 bg-primary shadow" style="width:900px; margin-left:200px">
                <div class="d-flex justify-content-between">
                    <h3 class="pt-2 pl-3">@userEvent.Title</h3>
                    <h5 class="mt-3">@userEvent.Location</h5>
                    <h6 class="mt-3 mr-3 ">Admin: @userEvent.AdminName</h6>
                </div>
                <hr class="mt-1 mb-3">

                <h5>TEAM 1</h5>
                @foreach (var position in userEvent.Positions.Take(userEvent.Positions.Count / 2).ToList())
                {
                    IDictionary<string, string> rv = new Dictionary<string, string>();
                    rv.Add("eventId", userEvent.Id.ToString());
                    rv.Add("positionId", position.Id.ToString());
                    StarModel starModel = new StarModel(position.EventId, position.Approved);
                    <div class="row">
                        <div class="col">
                            @position.Name:
                        </div>
                        <div class="col">
                            @if (@position.Approved.Name != null)
                            {
                                <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@position.Approved.Name">@position.Approved.Name</a>
                            }
                            else
                            {
                                <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled">Awaiting...</button>
                            }
                        </div>
                        <div class="col">
                            @if (@position.Approved.Name != null)
                            {
                                @await Html.PartialAsync($"_StarRatingPartial", starModel)
                            }
                        </div>
                        <div class="col">
                            @if (position.ToBeApproved.Exists(u => u.Name == User.Identity.Name))
                            {
                            <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
                            }
                            else if (@position.Approved.Name == null)
                            {
                                <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-all-route-data="@rv" asp-action="JoinUser">Join</a>
                            }
                            else if (position.Approved.Name == User.Identity.Name)
                            {
                                <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
                            }
                            else
                            {
                                <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Kick out</a>
                            }
                        </div>
                    </div>
                }
                <h5>TEAM 2</h5>
                @foreach (var position in userEvent.Positions.TakeLast(userEvent.Positions.Count / 2).ToList())
                {
                    IDictionary<string, string> rv = new Dictionary<string, string>();
                    rv.Add("eventId", userEvent.Id.ToString());
                    rv.Add("positionId", position.Id.ToString());
                    StarModel starModel = new StarModel(position.EventId, position.Approved);
                    <div class="row">
                        <div class="col">
                            @position.Name:
                        </div>
                        <div class="col">
                            @if (@position.Approved.Name != null)
                            {
                                <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@position.Approved.Name">@position.Approved.Name</a>
                            }
                            else
                            {
                                <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled">Awaiting...</button>
                            }
                        </div>
                        <div class="col">
                            @if (@position.Approved.Name != null)
                            {
                                @await Html.PartialAsync($"_StarRatingPartial", starModel)
                            }
                        </div>
                        <div class="col">
                            @if (position.ToBeApproved.Exists(u => u.Name == User.Identity.Name))
                            {
                                <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
                            }
                            else if (@position.Approved.Name == null)
                            {
                                <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-all-route-data="@rv" asp-action="JoinUser">Join</a>
                            }
                            else if (position.Approved.Name == User.Identity.Name)
                            {
                                <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
                            }
                            else
                            {
                                <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@position.EventId" asp-route-PositionId="@position.Id" asp-route-UserId="@position.Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Kick out</a>
                            }
                        </div>
                    </div>
                }

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h7 class="modal-title" id="exampleModalLabel">{Player Name}</h7>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="row d-flex" style="width:500px; height:500px">
                                    <div class="col">Description</div>
                                    <div class="col">Description</div>
                                    <div class="col">Description</div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" asp-controller="" asp-action="">View Profile</button>
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="my-2">
                <div class="d-flex justify-content-center">
                    <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="HomePage" asp-route-id="@userEvent.Id" asp-action="DetermineEventView">Info</a>
                </div>
            </div>
        </div>
    }
</div>

WebApp.Web/WebApp.Web/Views/AdminEvent/_AproovePartial.cshtml
@model List<WebApp.Web.Models.Event.PlayerModel>

@for (int i = 0; i < @Model.Count; i++)
{
    IDictionary<string, string> rv = new Dictionary<string, string>();
    rv.Add("eventId", Model[i].EventId.ToString());
    rv.Add("positionId", Model[i].PositionId.ToString());
    rv.Add("userId", Model[i].Id);
    <div class="row">
        <div class="column">
            <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@Model[i].Name" id="name">@Model[i].Name Wants to join!</a>
</div>
        <div class="column">
            <a class="button" role="button" asp-controller="AdminEvent" asp-route-EventId="@int.Parse(rv["eventId"])" asp-route-PositionId="@int.Parse(rv["positionId"])" asp-route-UserId="@rv["userId"]"  asp-action="ApproveUser" id="aproove">Approve</a>
            <a class="button" role="button" asp-controller="AdminEvent" asp-route-EventId="@int.Parse(rv["eventId"])" asp-route-PositionId="@int.Parse(rv["positionId"])" asp-route-UserId="@rv["userId"]"  asp-action="IgnoreUser" id="ignore">Ignore</a>
        </div>
    </div>
}
<br>
<style>
    #ignore {
        background-color: darkred;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        cursor: pointer;
    }

    #aproove {
        background-color: green;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        cursor: pointer;
    }

    #name {
        background-color: darkslategrey;
        border: none;
        color: white;
        padding: 5px 15px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 14px;
        margin: 4px 2px;
        cursor: pointer;
    }
</style>

WebApp.Web/WebApp.Web/Views/AdminEvent/_TeamPartial.cshtml
@model List<PositionModel>
@for (int i = 0; i < Model.Count; i++)
 {
    StarModel starModel = new StarModel(Model[i].EventId,Model[i].Approved);
    <div class="row">
        <h5>@Model[i].Name: </h5>
    </div>
    <div class="row">
        <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@Model[i].Approved.Name">@Model[i].Approved.Name</a>
        @if (@Model[i].Approved.Name != null)
        {
            @await Html.PartialAsync($"_StarRatingPartial", starModel)
        }
        @{
            IDictionary<string, string> rv = new Dictionary<string, string>();
            rv.Add("eventId", Model[i].EventId.ToString());
            rv.Add("positionId", Model[i].Id.ToString());
        }
        @if (@Model[i].ToBeApproved.Exists(u => u.Name == User.Identity.Name))
        {
            <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
        }
        else if (@Model[i].Approved.Name == null)
        {
            <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-all-route-data="@rv" asp-action="JoinUser">Join</a>
        }
        else if (Model[i].Approved.Name == User.Identity.Name)
        {
            <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@int.Parse(rv["eventId"])" asp-route-PositionId="@int.Parse(rv["positionId"])" asp-route-UserId="@Model[i].Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
        }
        else
        {
            <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@int.Parse(rv["eventId"])" asp-route-PositionId="@int.Parse(rv["positionId"])" asp-route-UserId="@Model[i].Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Kick out</a>
        }
    </div>

    @await Html.PartialAsync($"_AproovePartial", Model[i].ToBeApproved);
 }