WebApp.Web/WebApp.Web/Models/Event/EventBindingModel.cs
namespace WebApp.Web.Models.Event
{
    using System;
    using System.Collections.Generic;

    public class EventBindingModel
    {
        public int Id { get; set; }
        public EventBindingModel()
        {
            Positions = new List<PositionModel>();
        }

        public string Title { get; set; }

        public string ImageName { get; set; }

        public string ImageURL { get; set; }

        public string AdminId { get; set; }

        public string AdminName { get; set; }

        public string Location { get; set; }

        public string Description { get; set; }

        public DateTime Time { get; set; }

        public int SportId { get; set; }

        public List<PositionModel> Positions { get; set; }
    }
}

WebApp.Web/WebApp.Web/Models/Event/HomePageBinding.cs
namespace WebApp.Web.Models.Event
{
    using System.Collections.Generic;

    public class HomePageBinding
    {
        public HomePageBinding()
        {
            this.Modal = new EventBindingModel();
            this.Events = new List<EventBindingModel>();
        }

        public List<EventBindingModel> Events { get; set; }

        public EventBindingModel Modal { get; set; }
    }
}

WebApp.Web/WebApp.Web/Models/Event/PlayerModel.cs
namespace WebApp.Web.Models.Event
{
    public class PlayerModel
    {
        public string Name { get; set; }

        public int Rating { get; set; }

        public string Id { get; set; }

        public int EventId { get; set; }

        public int PositionId { get; set; }
    }
}

WebApp.Web/WebApp.Web/Models/Event/PositionModel.cs
namespace WebApp.Web.Models.Event
{
    using System.Collections.Generic;

    public class PositionModel
    {
        public PositionModel()
        {
            Approved = new PlayerModel();
            ToBeApproved = new List<PlayerModel>();
        }

        public int EventId { get; set; }

        public int Id { get; set; }

        public int Team { get; set; }

        public string Name { get; set; }

        public PlayerModel Approved { get; set; }

        public List<PlayerModel> ToBeApproved { get; set; }
    }
}

WebApp.Web/WebApp.Web/Models/Event/StarModel.cs
namespace WebApp.Web.Models.Event
{
    public class StarModel
    {
        public StarModel(int eventId, PlayerModel player)
        {
            this.EventId = eventId;
            this.Player = player;
        }
        public int EventId { get; set; }

        public PlayerModel Player { get; set; }
    }
}

WebApp.Web/WebApp.Web/Controllers/EventController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Mappers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.EventAttendanceService;
    using Services.RatingService;
    using System;
    using System.Linq;

    public class EventController : BaseController
    {
        private readonly IEventMapper eventMapper;
        private readonly UserManager<WebAppUser> userManager;
        private readonly IEventAttendanceService attendanceService;
        private readonly IRatingService ratingService;

        public EventController(
            UserManager<WebAppUser> userManager,
            IEventMapper eventMapper,
            IEventAttendanceService attendanceService,
            IRatingService ratingService)
        {
            this.ratingService = ratingService;
            this.userManager = userManager;
            this.eventMapper = eventMapper;
            this.attendanceService = attendanceService;
        }

        [Authorize]
        public IActionResult ViewEvent(Event dbEvent)
        {
            return View(eventMapper.ViewEvent(dbEvent));
        }

        [Authorize]
        public IActionResult JoinUser(JoinUserModel model)
        {
            int eventId = model.EventId;
            int positionId = model.PositionId;
            string joinId = this.userManager.GetUserId(User);

            if (!attendanceService.GetAllEventAttendeesForEvent(eventId).Any(a => a.UserId == joinId))
                attendanceService.RegisterUserForEvent(joinId, eventId, positionId).Wait();

            return RedirectToAction("DetermineEventView", "HomePage", new { Id = eventId });
        }
        public IActionResult LeaveUser(ApproveOrIgnoreUserModel model)
        {
            int eventId = model.EventId;
            int positionId = model.PositionId;
            string userId = model.UserId;

            attendanceService.RemoveUserAttendee(userId, eventId, positionId);
            return RedirectToAction("DetermineEventView", "HomePage", new { Id = eventId });
        }
        public IActionResult AddRating(RatingModel model)
        {
            string giverId = userManager.GetUserId(User);
            string receiverId = model.ReceiverId;
            int score = model.Rating;
            int eventId = model.EventId;

            ratingService.AddRating(eventId, giverId, receiverId, score, DateTime.Now);

            return RedirectToAction("DetermineEventView", "HomePage", new { Id = eventId });
        }
    }
}

WebApp.Web/WebApp.Web/Controllers/UsersController.cs
namespace WebApp.Web.Controllers
{
    using Domain;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Services.ScoreService;
    using System.Collections.Generic;
    using System.Linq;

    public class UsersController : BaseController
    {
        private readonly UserManager<WebAppUser> userManager;
        private readonly IScoreService scoreService;

        public UsersController(UserManager<WebAppUser> userManager, IScoreService scoreService)
        {
            this.userManager = userManager;
            this.scoreService = scoreService;
        }

        [Authorize]
        public IActionResult Profile(string name)
        {
            UserBindingModel model = new UserBindingModel
            {
                Name = name,
                Score = GetUserScores(name)
            };

            return View("Profile", model);
        }

        private List<UserScore> GetUserScores(string name)
        {
            string id = userManager.Users.FirstOrDefault(u => u.UserName == name).Id;
            List<Rating> rating = scoreService.GetAllData().Where(rid => rid.ReceiverId == id).ToList();
            List<UserScore> userScores = new List<UserScore>();
            foreach (var item in rating)
            {
                foreach (var score in item.Scores)
                {
                    userScores.Add(new UserScore()
                    {
                        CurrentDate = score.DateTime.ToShortDateString(),
                        Score = score.Points
                    });
                }
            }

            return userScores;
        }
    }
}

WebApp.Web/WebApp.Web/Views/Event/EventView.cshtml
@model WebApp.Web.Models.Event.EventBindingModel
@{
    ViewData["Title"] = "EventView";
}

<h1>@ViewData["EventView"]</h1>

<nav class="navbar p-0 m-0 justify-content-center d-flex bd-highlight sticky-top" id="centerNav">
    <form class="form-inline mt-2 bd-highlight">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search events" id="searchForm">
            <div class="input-group-append">
                <button class="btn" id="searching">
                    <img src="~/images/homepage/icons8-search-48.png" style="width: 2vw" />
                </button>
            </div>
        </div>
    </form>

    <button type="button" class="btn btn-outline-info mb-2 bd-highlight" data-toggle="modal" data-target="#exampleModalCenter" style="margin-left: 4rem">
        Create Event
    </button>

    <button type="button" class="btn btn-outline-info mb-2 bd-highlight ml-3">Create Event</button>
</nav>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form asp-action="EventView" method="post">
                <div class="modal-header d-flex justify-content-center">
                    <div class="form-group" style="width: 20rem">
                        <input asp-for="Name" type="text" class="form-control" id="Name" aria-describedby="NameInput" placeholder="Enter the event's name" />
                    </div>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>*@
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label for="eventLocation">Location</label>
                        <input asp-for="Location" type="text" class="form-control" id="eventLocation" aria-describedby="eventLocationInput" placeholder="Enter the event's location" />
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Example select</label>
                        <select asp-for="Type" @*asp-items="@(Html.GetEnumSelectList<Type>())"*@ class="form-control" id="exampleFormControlSelect1">
                            <option>Football</option>
                            <option>TableTennis</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea">Example textarea</label>
                        <textarea asp-for="Options" class="form-control" id="exampleFormControlTextarea" rows="3"></textarea>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" value="Create Event" @*class="btn btn-primary" *@></>
                </div>
            </form>
        </div>
    </div>
</div>

WebApp.Web/WebApp.Web/Views/Event/ViewEvent.cshtml
@{
    Layout = null;
}
@model EventBindingModel;
<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />
</head>
<div class="container">
    <div id="sidebar">
        @await Html.PartialAsync("_NavBarPartial")
    </div>
    <div id="content">
        <div class="row">
            <div class="column">
                <img src=@Model.ImageURL id="EventImage" />
                <center>@Model.Location</center>
            </div>
            <div class="column">
                <center><h1>@Model.Title<h3>@Model.Time.ToString()</h3></h1></center>
                <br />
                <br />
                <center>@Model.Description</center>
            </div>
        </div>
        <div class="row">
            <div class="column">
                <h3><center>TEAM 1</center></h3>
                @await Html.PartialAsync($"_TeamPartial", Model.Positions.Take(Model.Positions.Count / 2).ToList())
            </div>
            <div class="column">
                <h3><center>TEAM 2</center></h3>
                @await Html.PartialAsync($"_TeamPartial", Model.Positions.TakeLast(Model.Positions.Count / 2).ToList())
            </div>
        </div>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
    }

    .container {
        position: relative;
        padding: 10px;
        top: 0px;
        right: 0;
        left: 0;
        height: 1200px;
        width: 100%;
        min-width: 1000px;
    }

    #sidebar {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        width: 200px;
        height: 1000px;
    }

    #content {
        height: 700px;
        margin-left: 200px;
        padding: 10px;
    }

    #EventImage {
        position: relative;
        display: block;
        margin-left: auto;
        margin-right: auto;
        z-index: 1;
        margin-right: auto;
        height: 100%;
        max-height: 300px;
        width: 100%;
        max-width: 600px;
    }

    .column {
        float: left;
        width: 50%;
    }
</style>


WebApp.Web/WebApp.Web/Views/Event/_TeamPartial.cshtml
@model List<PositionModel>
 
    @for (int i = 0; i < Model.Count; i++)
     {
        StarModel starModel = new StarModel(Model[i].EventId,Model[i].Approved);
        <div class="row">
            <h5>@Model[i].Name: </h5>
        </div>
        <div class="row">
            <a type="button" class="btn btn-danger mx-3 mb-2" asp-controller="Users" asp-action="Profile" asp-route-name="@Model[i].Approved.Name">@Model[i].Approved.Name</a>
            @await Html.PartialAsync($"_StarRatingPartial", starModel);
            @{
                IDictionary<string, string> rv = new Dictionary<string, string>();
                rv.Add("eventId", Model[i].EventId.ToString());
                rv.Add("positionId", Model[i].Id.ToString());
            }
            @if (@Model[i].ToBeApproved.Exists(u => u.Name == User.Identity.Name))
            {
                <button type="button" class="btn btn-danger mx-3 mb-2" disabled="disabled" style="background-color:orange; color:white;">Waiting</button>
            }
            else if (@Model[i].Approved.Name == null)
            {
                <a class="btn btn-info btn mb-2 ml-4" role="button" asp-controller="Event" asp-route-EventId="@rv["eventId"]" asp-route-PositionId="@rv["positionId"]" asp-action="JoinUser">Join</a>
            }
            else if (Model[i].Approved.Name == User.Identity.Name)
            {
                <a type="button" class="btn btn-info btn mb-2 ml-4" asp-controller="Event" asp-route-EventId="@int.Parse(rv["eventId"])" asp-route-PositionId="@int.Parse(rv["positionId"])" asp-route-UserId="@Model[i].Approved.Id" asp-action="LeaveUser" style="background-color: red; color:white">Leave</a>
            }
            else
            {
                <a></a>
            }
        </div>
     }